# 资源管理与错误处理

# 资源管理 defer 调用

- 在函数结束时发生的动作，无论函数是正常返回还是异常返回。    
- defer 语句的执行顺序是先进后出，类似于栈的结构，先执行后面的。   
- 参数在 defer 语句时计算，

```go
package main

func tryDefer() {
	defer fmt.Println(1)    
    defer fmt.Println(2)
    fmt.Println(3)
    panic("error occurred")
	return 1
}
// 以上，无论代码 panic 或 return，都会执行 defer 语句
```

例如，操作文件

```go
package main

func fibonaqi() func() int {
	// 闭包实现斐波那契数列
	a, b := 0, 1

	return func() int {
		a, b = b, a+b
		return a
	}
}

func writeFile(fileName string) {
	// 写入文件
	file, err := os.Create(fileName)
	if err != nil {
		panic(err)
	}
	defer file.Close() // 先写的 defer， 最后执行这个defer，关闭文件

	writer := bufio.NewWriter(file)
	defer writer.Flush() // 倒数第二个 defer，先执行这个 defer，将缓存的数据写入文件
	f := fibonaqi()
	for i := 0; i < 50; i++ {
		fmt.Fprintln(writer, f())
	}
}

func main() {
	writeFile("fib.txt")
}

```

## defer 常用场景

- Open/Close
- Lock/Unlock
- PrintHeader/PrintFooter


# 错误处理 Error

erro 是一个接口，定义如下：

```go

type error interface {
    Error() string  // 返回错误信息字符串
}

err.Error() // 返回错误信息字符串
```

## 统一的错误处理

定义一个错误处理接口

使用 装饰器和闭包的原理， 将业务代码 被错误处理装饰

业务代码遇见错误只管 return，不用关心错误处理


## panic

- 停止当前函数执行
- 逐层向上返回，执行每一层的 defer
- 如果没有遇见 recover，程序退出
- Go 中的 panic 是一个很重的词，不要用于普通错误处理
- 应该仅在 defer 中使用 panic
- panic 的值可以是任何类型
- recover 可以捕获到 panic 的值
- recover 捕获到的 panic 可以重新 panic

```go

package main

import "fmt"

func main() {
	defer func() {
		panicContent := recover() // recover() 会返回 panic 的错误信息, 不一定是错误

		// 所以先检测 panicContent 是否是 error 类型
		if err, ok := panicContent.(error); ok {
			// 如果是 error 类型，则做出相应的处理
			fmt.Println(err)
		}
		// 如果不是 error 类型，不知如何处理，所以再次 panic
		panic(panicContent)
	}()

	panic("error occurred")
}
```